<?php
return [
    'db_host' => '127.0.0.1',
    'db_name' => 'legroup_db',
    'db_user' => 'legroup',
    'db_pass' => 'SENHA_DO_BANCO',
    'recaptcha_site_key' => 'SUA_CHAVE_DE_SITE',
    'recaptcha_secret_key' => 'SUA_CHAVE_SECRETA',
    'smtp_host' => 'email-ssl.com.br',
    'smtp_port' => 587,
    'smtp_encryption' => 'tls',
    'smtp_username' => 'edmilson.santos@legroup.com.br',
    'smtp_password' => 'SENHA_DO_EMAIL',
    'smtp_from_email' => 'edmilson.santos@legroup.com.br',
    'smtp_from_name' => 'Le Group',
    'google_analytics_id' => 'G-XXXXXXXXXX',
    'api_football_key' => 'SUA_CHAVE_API_FOOTBALL',
    'api_football_base_url' => 'https://v3.football.api-sports.io',
    'api_football_cache_seconds' => 300,
];
